/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.q5;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.StringTokenizer;

/**
 *
 * @author tran
 */
public class Main_frame extends javax.swing.JFrame {

    /**
     * Creates new form Main_frame
     */
    public Main_frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        format_dialog = new javax.swing.JDialog();
        full_name_lable = new javax.swing.JLabel();
        full_name_textField = new javax.swing.JTextField();
        modified_date_checkBox = new javax.swing.JCheckBox();
        submit_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        text_area = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        format_menuItem = new javax.swing.JMenuItem();

        full_name_lable.setText("Full name:");

        modified_date_checkBox.setText("The last modified date");

        submit_button.setText("Submit");
        submit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout format_dialogLayout = new javax.swing.GroupLayout(format_dialog.getContentPane());
        format_dialog.getContentPane().setLayout(format_dialogLayout);
        format_dialogLayout.setHorizontalGroup(
            format_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(format_dialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(full_name_lable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(format_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(modified_date_checkBox, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addComponent(full_name_textField))
                .addGap(18, 18, 18)
                .addComponent(submit_button)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        format_dialogLayout.setVerticalGroup(
            format_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(format_dialogLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(format_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(full_name_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(full_name_lable)
                    .addComponent(submit_button))
                .addGap(18, 18, 18)
                .addComponent(modified_date_checkBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        text_area.setColumns(20);
        text_area.setRows(5);
        text_area.setText("I close my eyes.  And the  flashbacks start . i'm standing there   On a balcony in a summer air");
        jScrollPane1.setViewportView(text_area);

        menu.setText("File");

        format_menuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        format_menuItem.setText("Format");
        format_menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                format_menuItemActionPerformed(evt);
            }
        });
        menu.add(format_menuItem);

        jMenuBar1.add(menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void format_menuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_format_menuItemActionPerformed
       format_dialog.pack();
       format_dialog.setVisible(true);
    }//GEN-LAST:event_format_menuItemActionPerformed

    private void submit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_buttonActionPerformed
       String text = text_area.getText(), res = "";
       
       StringTokenizer st1 = new StringTokenizer(text);

       boolean cap = true, space = false;
      while (st1.hasMoreTokens()){
           String app = st1.nextToken();
           
           app = app.toLowerCase();
           
           if (app.equals(".")){
               cap = true;
               space = false;
           }
           
           System.out.println(app);
           if (space)
                res += " ";
           if (cap){
               app = app.substring(0, 1).toUpperCase() + app.substring(1);
           }
           
           cap = app.contains(".") ? true : false;
           space = true;
           
           res += app;
       }
      
       text_area.setText(res + "\n" +  "Corrected by: " + full_name_textField.getText() + "\n" + (modified_date_checkBox.isSelected() ? "The last modified date " + LocalDate.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")) : ""));
       format_dialog.setVisible(false);
    }//GEN-LAST:event_submit_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog format_dialog;
    private javax.swing.JMenuItem format_menuItem;
    private javax.swing.JLabel full_name_lable;
    private javax.swing.JTextField full_name_textField;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menu;
    private javax.swing.JCheckBox modified_date_checkBox;
    private javax.swing.JButton submit_button;
    private javax.swing.JTextArea text_area;
    // End of variables declaration//GEN-END:variables
}
