/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.q4;

import java.awt.Component;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;

/**
 *
 * @author tran
 */
public class Main_frame extends javax.swing.JFrame {

    /**
     * Creates new form Main_frame
     */
    public Main_frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        option_buttonGroup = new javax.swing.ButtonGroup();
        calculate_dialog = new javax.swing.JDialog();
        select_name_lable = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        name_list = new javax.swing.JList<>();
        submit_button = new javax.swing.JButton();
        sum_radioButton = new javax.swing.JRadioButton();
        max_radioButton = new javax.swing.JRadioButton();
        min_radioButton = new javax.swing.JRadioButton();
        enter_numbers_label = new javax.swing.JLabel();
        enter_numbers_textField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        result_textArea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        send_to_menuItem = new javax.swing.JMenuItem();
        exit_menuItem = new javax.swing.JMenuItem();

        option_buttonGroup.add(sum_radioButton);
        option_buttonGroup.add(max_radioButton);
        option_buttonGroup.add(min_radioButton);

        select_name_lable.setText("Select name:");

        name_list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Dang Chau Anh", "Ha Kien Trung", "Nam Vinh Ho", "Le Quy Chi" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(name_list);

        submit_button.setText("Submit");
        submit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_buttonActionPerformed(evt);
            }
        });

        sum_radioButton.setText("Sum");

        max_radioButton.setText("Max");

        min_radioButton.setText("Min");

        javax.swing.GroupLayout calculate_dialogLayout = new javax.swing.GroupLayout(calculate_dialog.getContentPane());
        calculate_dialog.getContentPane().setLayout(calculate_dialogLayout);
        calculate_dialogLayout.setHorizontalGroup(
            calculate_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calculate_dialogLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(calculate_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(calculate_dialogLayout.createSequentialGroup()
                        .addComponent(select_name_lable)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(calculate_dialogLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addComponent(submit_button)
                        .addGap(55, 55, 55))
                    .addGroup(calculate_dialogLayout.createSequentialGroup()
                        .addGroup(calculate_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(min_radioButton)
                            .addComponent(max_radioButton)
                            .addComponent(sum_radioButton))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        calculate_dialogLayout.setVerticalGroup(
            calculate_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(calculate_dialogLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(calculate_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(submit_button)
                    .addGroup(calculate_dialogLayout.createSequentialGroup()
                        .addComponent(select_name_lable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(sum_radioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(max_radioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(min_radioButton)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        enter_numbers_label.setText("Enter the list of numbers");

        enter_numbers_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enter_numbers_textFieldActionPerformed(evt);
            }
        });

        result_textArea.setColumns(20);
        result_textArea.setRows(5);
        jScrollPane1.setViewportView(result_textArea);

        menu.setText("File");

        send_to_menuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        send_to_menuItem.setText("Send to");
        send_to_menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_to_menuItemActionPerformed(evt);
            }
        });
        menu.add(send_to_menuItem);

        exit_menuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        exit_menuItem.setText("Exit");
        exit_menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_menuItemActionPerformed(evt);
            }
        });
        menu.add(exit_menuItem);

        jMenuBar1.add(menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(enter_numbers_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enter_numbers_textField))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enter_numbers_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enter_numbers_label))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void send_to_menuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_to_menuItemActionPerformed
       calculate_dialog.pack();
        calculate_dialog.setVisible(true);
    }//GEN-LAST:event_send_to_menuItemActionPerformed

    private void exit_menuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_menuItemActionPerformed
       int option = JOptionPane.showConfirmDialog(null,  "Do you really want to exit", "Question", JOptionPane.YES_NO_OPTION);
       if (option == JOptionPane.YES_OPTION){
           dispose();
       }
    }//GEN-LAST:event_exit_menuItemActionPerformed

    private void submit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_buttonActionPerformed
      String t = "";
      t += "Calculated by : " +  name_list.getSelectedValue() + "\n"; 
      
      String numbers[] =  enter_numbers_textField.getText().split(" ");
      int number_list[] = new int[numbers.length];

      for (int i = 0; i < numbers.length; i ++){
          number_list[i] = Integer.valueOf(numbers[i]);
      }
      
      int n = numbers.length;
      if (max_radioButton.isSelected()){
          t += "Max = ";
          int max_val = Integer.MIN_VALUE;
          for (int i : number_list){
              max_val = Integer.max(i, max_val); 
          }
          
          t += max_val + "\n";
      }
      
      else if (min_radioButton.isSelected()){
           t += "Min  = ";
          int min_val = Integer.MAX_VALUE;
          for (int i : number_list){
              min_val = Integer.min(i, min_val); 
          }
          
          t += min_val + "\n";
      }
      
      else if (sum_radioButton.isSelected()){
          t += "Sum : ";
          int s = 0;
          for (int i : number_list){
             s += i; 
          }
          t += s + "\n";
      }
      calculate_dialog.setVisible(false);
      result_textArea.setText(t);
    }//GEN-LAST:event_submit_buttonActionPerformed

    private void enter_numbers_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enter_numbers_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enter_numbers_textFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog calculate_dialog;
    private javax.swing.JLabel enter_numbers_label;
    private javax.swing.JTextField enter_numbers_textField;
    private javax.swing.JMenuItem exit_menuItem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton max_radioButton;
    private javax.swing.JMenu menu;
    private javax.swing.JRadioButton min_radioButton;
    private javax.swing.JList<String> name_list;
    private javax.swing.ButtonGroup option_buttonGroup;
    private javax.swing.JTextArea result_textArea;
    private javax.swing.JLabel select_name_lable;
    private javax.swing.JMenuItem send_to_menuItem;
    private javax.swing.JButton submit_button;
    private javax.swing.JRadioButton sum_radioButton;
    // End of variables declaration//GEN-END:variables
}
