/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.q3;

import javax.swing.JOptionPane;

/**
 *
 * @author tran
 */
public class Bai3 extends javax.swing.JFrame {

    /**
     * Creates new form Bai3
     */
    public Bai3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login_dialog = new javax.swing.JDialog();
        name_text_field = new javax.swing.JTextField();
        name_lable = new javax.swing.JLabel();
        email_text_field = new javax.swing.JTextField();
        email_lable = new javax.swing.JLabel();
        confirm_login_button = new javax.swing.JButton();
        show_email_checkbox = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        text_area = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        login_menu_item = new javax.swing.JMenuItem();
        exit_menu_item = new javax.swing.JMenuItem();

        name_lable.setText("Name:");

        email_lable.setText("Email");

        confirm_login_button.setText("Confirm");
        confirm_login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirm_login_buttonActionPerformed(evt);
            }
        });

        show_email_checkbox.setText("Show email");
        show_email_checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_email_checkboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout login_dialogLayout = new javax.swing.GroupLayout(login_dialog.getContentPane());
        login_dialog.getContentPane().setLayout(login_dialogLayout);
        login_dialogLayout.setHorizontalGroup(
            login_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(login_dialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(login_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(login_dialogLayout.createSequentialGroup()
                        .addGroup(login_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(name_lable)
                            .addComponent(email_lable))
                        .addGap(18, 18, 18)
                        .addGroup(login_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(name_text_field, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                            .addComponent(email_text_field))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(confirm_login_button))
                    .addGroup(login_dialogLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(show_email_checkbox)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        login_dialogLayout.setVerticalGroup(
            login_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(login_dialogLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(login_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name_lable)
                    .addComponent(name_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirm_login_button))
                .addGap(53, 53, 53)
                .addGroup(login_dialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email_text_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email_lable))
                .addGap(32, 32, 32)
                .addComponent(show_email_checkbox)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        text_area.setColumns(20);
        text_area.setRows(5);
        text_area.setText("Ha noi ngay nang nong! Toi met moi den lop. Toi co gang tap trung hoc bai, vi toi biet sap thi PE roi. Nhung hom nay toi thay hoc kha vao, co the toi lam duoc bai");
        jScrollPane1.setViewportView(text_area);

        menu.setText("File");

        login_menu_item.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.CTRL_MASK));
        login_menu_item.setText("Login");
        login_menu_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_menu_itemActionPerformed(evt);
            }
        });
        menu.add(login_menu_item);

        exit_menu_item.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        exit_menu_item.setText("Exit");
        exit_menu_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_menu_itemActionPerformed(evt);
            }
        });
        menu.add(exit_menu_item);

        jMenuBar1.add(menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_menu_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_menu_itemActionPerformed
        login_dialog.pack();
        login_dialog.setVisible(true);
    }//GEN-LAST:event_login_menu_itemActionPerformed

    private void exit_menu_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_menu_itemActionPerformed
             int option =  JOptionPane.showConfirmDialog(null, "Do you really want to exit application?", "Question", JOptionPane.YES_NO_OPTION);
             if (option == JOptionPane.YES_OPTION){
                 
                 super.dispose();
             }
    }//GEN-LAST:event_exit_menu_itemActionPerformed

    private void show_email_checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_email_checkboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_show_email_checkboxActionPerformed

    private void confirm_login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirm_login_buttonActionPerformed
        String s = text_area.getText(), res;
        int c = 0,  i = 0;
        while ((i = s.indexOf("toi", i)) != -1){
            c ++;
            i ++;
        }
        res = "Teacher: " + name_text_field.getText() + "\n";
        if (c > 4)
            res += "The document have too many toi\n" ;
        else if (c < 2)
            res += "The document have too few toi\n";
        else
            res += "The document is OK\n";
        if (show_email_checkbox.isSelected())
            res += email_text_field.getText() + "\n";
        text_area.setText(res);
        login_dialog.dispose();
    }//GEN-LAST:event_confirm_login_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bai3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirm_login_button;
    private javax.swing.JLabel email_lable;
    private javax.swing.JTextField email_text_field;
    private javax.swing.JMenuItem exit_menu_item;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JDialog login_dialog;
    private javax.swing.JMenuItem login_menu_item;
    private javax.swing.JMenu menu;
    private javax.swing.JLabel name_lable;
    private javax.swing.JTextField name_text_field;
    private javax.swing.JCheckBox show_email_checkbox;
    private javax.swing.JTextArea text_area;
    // End of variables declaration//GEN-END:variables
}
